version: '3.8'

services:
  app:
    image: 'venus-backend:250422'
    build:
      context: .
    container_name: venus_backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    container_name: venus-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    ports:
      - '5490:5432'
  frontend:
    image: 'venus-frontend:250422'
    build:
      context: .
    container_name: venus_frontend
    depends_on:
      - app
    ports:
      - '3000:3000'
    environment:
      - API_URL=app
